name: publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          cd /usr/bin
          curl -L https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf -
          curl -L https://github.com/tdewolff/minify/releases/download/v2.9.10/minify_linux_amd64.tar.gz | sudo tar xvzf -
          curl -L https://github.com/cloudflare/wrangler/releases/download/v1.12.3/wrangler-v1.12.3-x86_64-unknown-linux-musl.tar.gz | sudo tar xvzf - --strip=1

      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build website
        run: ./build.sh

      - name: Publish to Cloudflare
        run: wrangler publish --env production
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
